# Generated by Django 3.1 on 2020-09-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('code', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('max_capacity', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
    ]
